import { Toaster } from "react-hot-toast";
import "./globals.css";
import { ReduxProvider } from "./redux/provider";
 

export const metadata = {
  title: "Eco for practice",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`  antialiased`}
      >
        <ReduxProvider>{children}</ReduxProvider>
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
